### PR TITLE
Fix coordinator architecture

### LINKED ISSUE #680: Coordinator may override manually promoted leader
The coordinator makes decisions basing on local context:

https://github.com/tarantool/cartridge/blob/249f95571d557579aa041a7c6a1ad4a47387ebde/cartridge/roles/coordinator.lua#L58-L68

But leader appointments are saved directly to external storage and not to local context:

https://github.com/tarantool/cartridge/blob/249f95571d557579aa041a7c6a1ad4a47387ebde/cartridge/roles/coordinator.lua#L285-L311

It means manual appointment may me overridden by the next failover triggering.

### LINKED ISSUE #681: Inactive coordinators spam new connections
Usually there may be several instances with coordinator role enabled, but only one can acquire lock in external storage. In the mean time, other coordinators (inactive) keep trying, but with every attempt to acquire a lock it creates new connection, which is closed soon. This is no good and should be fixed

### PR DESCRIPTION
**Pull request by rosik**
There are several problems:

    1. While external storage is locked by active coordinator others spam
       new connections (#681).
    2. Coordinator may override manually promoted leader (#680).
    3. Manual promotion and take_control_loop are subkect to several race
       conditions.
    4. Coordinator didn't handle URI change properly.

    This patch introduces new module - state provider client. The client is
    created once for one set of parameters and handles reconnections.

    While reconnecting is opaque in state provider client, it's only
    achieved by explicitly calling get_session method. Within a session no
    reconnections are possible. While using the same session the coordinator
    can be sure that no race conditions result in inconsistency.

    The session state machine corresponds to the one of netbox connection:
    initial -> active -> error/closed.

    The client caches the session and creates new one only if the previous
    has died.

I didn't forget about

- [x] Tests

Close #680 
Close #681

### CODE REVIEW

File: cartridge/roles/coordinator.lua [hunk 1]
```diff
@@ -2,22 +2,21 @@ local log = require('log')
...
 local AppointmentError = errors.new_class('AppointmentError')
 local CoordinatorError = errors.new_class('CoordinatorError')
-local NetboxConnectError = errors.new_class('NetboxConnectError')
 
 vars:new('membership_notification', membership.subscribe())
 vars:new('connect_fiber', nil)
 vars:new('topology_cfg', nil)
-vars:new('conn', nil)
+vars:new('client', nil)
+vars:new('session', nil)
```
Comment (olegrok) [inline cartridge/roles/coordinator.lua:19]: If "client" contains "session". I don't see reasons to store session in vars as it could be easily obtained via "client:get_session()".

File: cartridge/roles/coordinator.lua [hunk 2]
```diff
@@ -195,47 +194,53 @@ local function take_control(uri)
         end
 
         if pcall(fiber.status, control_fiber) == 'dead'
```
Comment (olegrok) [inline cartridge/roles/coordinator.lua:196]: This condition is always "false". `true/false` ~= 'dead'

File: cartridge/roles/coordinator.lua [hunk 3]
```diff
@@ -195,47 +194,53 @@ local function take_control(uri)
...
-    if vars.connect_fiber == nil then
-        return
-    elseif vars.connect_fiber:status() ~= 'dead' then
-        vars.connect_fiber:cancel()
+    if vars.connect_fiber ~= nil then
+        pcall(fiber.cancel, vars.connect_fiber)
+        vars.connect_fiber = nil
+    end
+
+    if vars.session ~= nil then
```
Comment (olegrok) [inline cartridge/roles/coordinator.lua:235]: I suppose that `vars.client:drop_session()` should be enough to drop session. I don't understand such duplication.

File: cartridge/roles/coordinator.lua [hunk 4]
```diff
@@ -247,7 +252,22 @@ local function apply_config(conf, _)
         return true
     end
 
-    if failover_cfg.state_provider ~= 'tarantool' then
+    if failover_cfg.state_provider == 'tarantool' then
+        local params = assert(failover_cfg.tarantool_params)
+
+        if vars.client == nil
```
Comment (olegrok) [inline cartridge/roles/coordinator.lua:258]: It would be great if you find a way to generalise such logic. You change it here if ~something~ is changed. I suppose you could organise configuration in a way then `cmpdeeply(new, old)` makes you call client:stop/drop and reconnect then.

File: cartridge/roles/coordinator.lua [hunk 5]
```diff
@@ -298,34 +313,47 @@ local function appoint_leaders(leaders)
...
 
         if server.replicaset_uuid ~= k then
-            return nil, AppointmentError:new('Server "%s" does not belong to replicaset "%s"', v, k)
+            return nil, AppointmentError:new(
+                "Server %q doesn't belong to replicaset %q", v, k
+            )
         end
+    end
+
+    local session = vars.session
```
Comment (olegrok) [inline cartridge/roles/coordinator.lua:335]: If you don't want to force reconnect client if session is broken/closed/... add "client.get_session_or_nil" function or smth else with better name.

File: cartridge/roles/coordinator.lua [hunk 6]
```diff
@@ -123,68 +108,76 @@ local function control_loop(conn)
...
             and (decision.immunity < next_moment)
             then
                 next_moment = decision.immunity
             end
         end
 
+        assert(next_moment >= now)
         vars.membership_notification:wait(next_moment - now)
-    until not pcall(fiber.testcancel)
+    until not pcall(fiber.testcancel) or not session:is_locked()
```
Comment (olegrok) [inline cartridge/roles/coordinator.lua:131]: Looks strange.

`until not pcall(fiber.testcancel)` is an infinite loop. not session:is_locked() potentially is not infinite. And this mixture looks strange.

Consider a way to move `not session:is_locked()` into loop body and add explicit break.

File: cartridge/stateboard-client.lua [hunk 7]
```diff
@@ -0,0 +1,158 @@
...
+
+    return session.connection:is_connected()
+        and session.lock_acquired
+end
+
+local function is_alive(session)
+    checks('stateboard_session')
+    assert(session.connection ~= nil)
+
+    return session.connection.state == 'initial'
```
Comment (olegrok) [inline cartridge/stateboard-client.lua:73]: image

Let's consider "alive" only as "connection:is_connected"

Comment (rosik) [reply cartridge/stateboard-client.lua:73]: Nope. We create session with `wait_connected = false` flag. "Initial" state is appropriate for the session to be counted as alive

Comment (olegrok) [reply cartridge/stateboard-client.lua:73]: But there are also "connecting", "auth" states. And there is no difference between "initial" and these states.

File: cartridge/roles/coordinator.lua [hunk 8]
```diff
@@ -123,119 +108,136 @@ local function control_loop(conn)
...
+        then
             break
         end
     until not pcall(fiber.testcancel)
 
-    pcall(conn.close, conn)
-    pcall(fiber.cancel, control_fiber)
-    vars.conn = nil
+    session:drop()
+    pcall(function()
```
Comment (olegrok) [inline cartridge/roles/coordinator.lua:202]: pcall(fiber.cancel, control_fiber) looks more appropriate IMO. Feel free to ignore.
