### PR TITLE
Fix remote control bind

### LINKED ISSUE #2190: АльфаБанк - Tarantool support
В tdg1 216+ инстансы теперь слушают не все интерфейсы (как это было в 179-й: 0.0.0.0), а только тот, который разрешиться по DNS для имени из конфигурации (деплойника).

Почему dns-имена разрешаются в 127.0.0.1 только в одном месте, где оно подставляется туда, где было 0.0.0.0, а при коннектах всё ок - разрешаются в нормальные ip-адреса.
При этом инстансы "не видят" друг друга по bin-портам. Сами инстансы в рабочем состоянии. В логах: remote control bind to 127.0.0.1:3030

В логах именно 127.0.0.1 или 127.0.1.1.
Полностью, например, так:

Remote control bound to 127.0.1.1:3030

### PR DESCRIPTION
**Pull request by yngvar-antonsson**
I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation

Close #2190

### CODE REVIEW

File: cartridge/confapplier.lua [hunk 1]
```diff
@@ -822,18 +824,7 @@ local function init(opts)
     vars.ssl_client_key_file = opts.ssl_client_key_file
     vars.ssl_client_password = opts.ssl_client_password
 
-    local parts = uri_tools.parse(opts.advertise_uri)
-    local family = parts.ipv6 and 'AF_INET6' or 'AF_INET'
-    local addrinfo, err = socket.getaddrinfo(
```
Comment (yngvar-antonsson) [inline cartridge/confapplier.lua:827]: filter out localhosts

**Review by filonenko-mikhail — APPROVED** [review]
