### PR TITLE
Pshipilov

### LINKED ISSUE #398: Race condition in console_sock_test
The test is flaky.

```text
Failed tests:
-------------
1) console_sock.test_console_sock
...rojects/cartridge/test/integration/console_sock_test.lua:37: expected: true, actual: false
stack traceback:
	...rojects/cartridge/test/integration/console_sock_test.lua:37: in function 'console_sock.test_console_sock'
```

The test should be combined with notify socket testing: at first, wait for notification, then check console sock is ready.

### PR DESCRIPTION
**Pull request by DHorrible**
Fix console socket test. 
Add waiting for notification of readiness from the server.
Close #398

### CODE REVIEW

File: test/integration/console_sock_test.lua [hunk 1]
```diff
@@ -20,11 +21,29 @@ g.before_all = function()
...
+            NOTIFY_SOCKET = fio.pathjoin(tmpdir, '/notify.sock')
         },
     })
+    -- build notify socket
+    local notify_socket = assert(socket('AF_UNIX', 'SOCK_DGRAM', 0), 'Can not create socket')
+    if fio.stat(server.env.NOTIFY_SOCKET) then
+        assert(fio.unlink(server.env.NOTIFY_SOCKET))
+    end
+    assert(notify_socket:bind('unix/', server.env.NOTIFY_SOCKET), notify_socket:error())
+    fio.chmod(server.env.NOTIFY_SOCKET, tonumber('0666', 8))
```
Comment (rosik) [inline test/integration/console_sock_test.lua]: unnecessary

File: test/integration/console_sock_test.lua [hunk 2]
```diff
@@ -20,11 +21,29 @@ g.before_all = function()
...
     server:start()
-    t.helpers.retrying({}, function() server:graphql({query = '{}'}) end)
+    -- wait notify
+    while true do
```
Comment (rosik) [inline test/integration/console_sock_test.lua]: use `retrying()` as before instead of `while true`. Imagine the notification stops working for some reason one day. So the test will hang until gitlab kills it. You should rely on `retrying()` instead.

File: test/integration/console_sock_test.lua [hunk 3]
```diff
@@ -20,11 +21,29 @@ g.before_all = function()
...
+        if notify_socket:readable(1) then
+            local msg = notify_socket:recv()
+            log.info(msg)
+            if msg:match('READY=1') then
+                fio.unlink(server.env.NOTIFY_SOCKET)
```
Comment (rosik) [inline test/integration/console_sock_test.lua]: Unnecessary

File: test/integration/console_sock_test.lua [hunk 4]
```diff
@@ -20,11 +20,21 @@ g.before_all = function()
...
+            TARANTOOL_CONSOLE_SOCK = fio.pathjoin(tmpdir, '/foo.sock'),
+            NOTIFY_SOCKET = fio.pathjoin(tmpdir, '/notify.sock')
         },
     })
+    local notify_socket = assert(socket('AF_UNIX', 'SOCK_DGRAM', 0), 'Can not create socket')
+    assert(notify_socket:bind('unix/', server.env.NOTIFY_SOCKET), notify_socket:error())
     server:start()
-    t.helpers.retrying({}, function() server:graphql({query = '{}'}) end)
+    t.helpers.retrying({}, function() 
+        while not notify_socket:readable(1) do
```
Comment (rosik) [inline test/integration/console_sock_test.lua]: This condition is wrong. You try to call recv when socket isn't readable. Don't implement a loop at all, `retrying` already implies it.
