### PR TITLE
Fix flaky etcd tests

### LINKED ISSUE #996: [2pt] Etcd tests are flaky
https://gitlab.com/tarantool/cartridge/-/jobs/678622949
https://gitlab.com/tarantool/cartridge/-/jobs/678622943

### PR DESCRIPTION
**Pull request by Steap2448**
Fix race conditions in the failover_stateful.etcd2 and etcd2_client tests.

I didn't forget about

- [x] Tests
- [ ] Changelog
- [ ] Documentation

Close #996

### CODE REVIEW

File: test/integration/etcd2_client_test.lua [hunk 1]
```diff
@@ -1,5 +1,5 @@
 local t = require('luatest')
-local g = t.group()
+local g = t.group('integration.etcd2_client_test')
```
Comment (rosik) [inline test/integration/etcd2_client_test.lua:2]: why? the default value is derived from filename, in this case - "integration.etcd2_client" (without "_test")

Comment (Steap2448) [reply test/integration/etcd2_client_test.lua:2]: For debug purposes only. Forgot to remove it
