### PR TITLE
rpc: wait until config commit finishes if role is unavailable

### LINKED ISSUE #1575: Fix `rpc.get_candidates` function
```lua
local rpc = require('cartridge.rpc')
local _, err = rpc.call('my_role', ...)
local candidates = rpc.get_candidates('my_role')
log.info(err)
log.info(candidates)
```

Sometimes the code above may log `["localhost:11002"]` and `RemoteCallError: "localhost:11002": Role "my_role" unavailable` simultaneously. It means that `rpc.get_candidates` returns those instances that are not actually alive, i.e. nothing can be done on them. So, it's incorrect behavior of `rpc.get_candidates`.

This seems to be due to the slow writing of the configuration backup to disk. As a result, we may have such that all instances are in the `RolesConfigured` status, but the config has not yet begun to be applied to some of the instances (in the example it's `localhost:11002`).

To reproduce this error, you can:
- create 2 instances (with 11001 and 11002 ports);
- assign `my_role` only to the second instance;
- insert code:

  ```lua
  if confapplier.get_advertise_uri() == 'localhost:11002' then
      local fiber = require('fiber')
      fiber.sleep(3)
  end
  ```
  
  to the 135 line in `cartridge/twophase.lua` file:

  https://github.com/tarantool/cartridge/blob/e887629b34e0c6d13a7916226a4e327c90b59f45/cartridge/twophase.lua#L130-L136

### PR DESCRIPTION
**Pull request by olegrok**
There is a raise condition. We could commit config locally but it
could be in progress on some instance. Before this patch user got
unexpected "Role X unavailable" from instance where such role was
assumed.
Solution is an optimistic approach - detect config apply and try
to wait until it will be finished.

Closes #1575

### CODE REVIEW

**Comment by yngvar-antonsson** [comment]
Have you tested it on TDG?

**Comment by olegrok** [comment]
> Have you tested it on TDG?

It seems to be ok.
However I found one more issue with #1575 that this patch is not fix.

If there are three instances A, B, C and A applies config and disables some role on C. If B still has old version of configuration (not committed yet) and thinks that C has role that is actually disabled we will still have such error "Role unavailable".

So patch fixes only one (probably the most often) flow.

File: test/integration/get_candidates_test.lua [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+           res = res,
+           err = err,
+           candidates = candidates,
+       }
+   end)
+
+    t.assert_type(res.err, 'nil')
+    t.assert_equals(res.res, 'woof')
+    t.assert_equals(res.candidates, {g.B1.advertise_uri})
+end
```
Comment (yngvar-antonsson) [inline test/integration/get_candidates_test.lua:95]: Add newline

File: cartridge/rpc.lua [hunk 2]
```diff
@@ -22,6 +23,16 @@ local function call_local(role_name, fn_name, args)
     checks('string', 'string', '?table')
     local role = service_registry.get(role_name)
 
+    if role == nil then
+        -- Optimistic approach.
+        -- Probably instance in apply config state so
+        -- we need to wait a bit until it finishes.
+        if twophase.wait_config_release() and
+                confapplier.wish_state('RolesConfigured') == 'RolesConfigured' then
```
Comment (yngvar-antonsson) [inline cartridge/rpc.lua:31]:
```suggestion
        if twophase.wait_config_release()
        and confapplier.wish_state('RolesConfigured') == 'RolesConfigured' then
```

File: cartridge/twophase.lua [hunk 3]
```diff
@@ -80,6 +89,26 @@ local function get_apply_config_timeout()
     return vars.options.apply_config_timeout
 end
 
+local function wait_config_release(timeout)
```
Comment (yngvar-antonsson) [inline cartridge/twophase.lua:92]: Maybe we should log a warning while waiting?

Comment (yngvar-antonsson) [inline cartridge/twophase.lua:92]: Please add docs for this function

**Review by yngvar-antonsson — CHANGES_REQUESTED** [review]

File: cartridge/twophase.lua (hunk 3 above)
Comment (olegrok) [reply cartridge/twophase.lua:104]: It's a critical section. We can't just log here because it could spam logs.

Comment (olegrok) [reply cartridge/twophase.lua:104]: Done

**Review by yngvar-antonsson — APPROVED** [review]
