### PR TITLE
Fix quering issues on uninitialized instance

### LINKED ISSUE #700: Querying issues fail on uninitialized instance
```text
/opt/cartridge/cartridge/issues.lua:122: attempt to index local 'topology_cfg' (a nil value)
```

Blocker for #690

### PR DESCRIPTION
**Pull request by HustonMmmavr**
Close #700

I didn't forget about

- [x] Tests
- [x] Changelog
- [x] Documentation

### CODE REVIEW

File: test/integration/api_uninitialized_test.lua [hunk 1]
```diff
@@ -193,3 +193,13 @@ function g.test_rpc()
         err = 'No remotes with role "myrole-permanent" available',
     })
 end
+
+function g.test_issues_uninitialized_instance()
```
Comment (rosik) [inline test/integration/api_uninitialized_test.lua]:
```suggestion
function g.test_issues()
```
