### PR TITLE
Autodisable broken instances

### LINKED ISSUE #2261: Disable broken instances automatically
When Cartridge sees that instance switched to an unrecoverable condition, we should automatically disable such instances.

### PR DESCRIPTION
**Pull request by yngvar-antonsson**
I didn't forget about

- [x] Tests
- [x] Changelog
- [x] Documentation

Close #2261

### CODE REVIEW

File: cartridge/issues.lua [hunk 1]
```diff
@@ -711,9 +716,31 @@ local function list_on_cluster()
...
+        and (state == 'InitError' or state == 'BootError')
+        then
+            for k, v in pairs(topology_cfg.servers) do
+                if v.uri == uri then
+                    uuid = k
+                    goto uuid_found
+                end
+            end
+            ::uuid_found::
+            table.insert(unrecoverable_uuids, uuid)
```
Comment (filonenko-mikhail) [inline cartridge/issues.lua:730]: if no trigger uuid_found, issue contains nil info
