### PR TITLE
Disable vshard while applying config

### LINKED ISSUE #2325: Альфа-банк+ВК_проект Профиль клиента vShard call failed bug 1
https://jira.vk.team/browse/TNT-1392 

При Аварии на физ.сервере - неисправность дисковой подсистемы - отформатировались PVC, некорректная работа раннеров / vSharda, которые направляли запросы на неактивные инстансы кластера (в том числе и на чтение). Так же не получилось задизейблить проблемные инстансы, чтобы восстановить консистентность кластера для корректной работы.

Создан постпортем с подробной хронологией разбора и восстановления работы кластера https://confluence.vk.team/pages/viewpage.action?pageId=1557218777

Консистентность кластера восстановлена перезагрузкой раннеров для устранения проблемы с vShard (перечитывание всего конфига, проверка доступности всех инстансов). Восстановление инстансов ребутстрапом

 1. TDG должен начать нормально обрабатывать случай, когда он несконфигурирован, а не выбрасывать непонятные ошибки LuaJIT.

### PR DESCRIPTION
**Pull request by yngvar-antonsson**
When instances receive an OperationError or a ConnectingFullmesh state, you can't really use Tarantool. Previously, we decided to disable Vshard after encountering errors in apply_config, but now we see that this is not enough. Users can receive errors after a restart, and to avoid this, we should disable vshard before the end of the first apply_config. Moreover, I decided to add an env variable to let users control whether they should disable vshard on each apply_config or not.

I didn't forget about

- [x] Tests
- [x] Changelog
- [x] Documentation

Close #2325

### CODE REVIEW

File: cartridge/roles/vshard-storage.lua [hunk 1]
```diff
@@ -67,12 +68,23 @@ local function init()
...
+        vars.auto_disable = opts.auto_disable_vshard_storage
     end
 end
 
+local first_apply = true
+local function before_apply_config(_)
+    if first_apply or vars.auto_disable then
+        vshard.storage.disable()
+    end
+    first_apply = false
```
Comment (olegrok) [inline cartridge/roles/vshard-storage.lua:84]: Not sure it matters but in case of roles hot reload this value will be reloaded as well.

**Comment by a1div0** [comment]
Является частью решения проблемы TNT-1390

File: test/integration/vshard_storage_disabling_test.lua [hunk 2]
```diff
@@ -1,37 +1,16 @@
 local fio = require('fio')
 local t = require('luatest')
-local g = t.group()
+local g_auto = t.group('vshard_storage_disabling.auto')
+local g_default = t.group('vshard_storage_disabling.default')
```
Comment (yngvar-antonsson) [inline test/integration/vshard_storage_disabling_test.lua:4]:
```suggestion
local g_auto = t.group('integration.vshard_storage_disabling.auto')
local g_default = t.group('integration.vshard_storage_disabling.default')
```

File: cartridge/roles/vshard-storage.lua [hunk 3]
```diff
@@ -67,12 +69,28 @@ local function init()
...
 
+-- A bit of rawget magic to avoid disabling vshard.storage
+-- after a hotreload
+if rawget(_G, '__cartridge_vshard_first_apply_config') == nil then
+    rawset(_G, '__cartridge_vshard_first_apply_config', true)
+end
+local function before_apply_config(_)
+    local first_apply = rawget(_G, '__cartridge_vshard_first_apply_config')
+    if first_apply or vars.auto_disable then
+        vshard.storage.disable()
```
Comment (a1div0) [inline cartridge/roles/vshard-storage.lua:88]: What happens when we turn off vshard storage?

Comment (yngvar-antonsson) [reply cartridge/roles/vshard-storage.lua:88]: It stops accepting incoming requests until `enable` is called..

File: cartridge/failover.lua [hunk 4]
```diff
@@ -312,6 +312,21 @@ local function apply_config(mod)
     )
 end
 
+local function before_apply_config(mod)
```
[the remark this answers is not in the document]
Comment (yngvar-antonsson) [reply cartridge/failover.lua:315]: `mod` is a cartridge role

File: cartridge/roles/vshard-storage.lua (hunk 3 above)
Comment (a1div0) [reply cartridge/roles/vshard-storage.lua:88]: So when we apply the configuration, we will deny service? I don't think that's good. Is it possible to only deny service requests and accept client requests?

**Review by olegrok — APPROVED** [review]
