### PR TITLE
Fix replication info in the WebUI

### LINKED ISSUE #1283: No value provided for non-null ReplicaStatus
```text
cartridge.srv-1 | 2021-03-02 16:32:09.842 [2835137] main/416/http/127.0.0.1:39254 graphql.lua:313 E> Graphql execution failed: No value provided for non-null ReplicaStatus "???"
cartridge.srv-1 | stack traceback:
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/graphql/execute.lua:186: in function 'completeValue'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/graphql/execute.lua:213: in function 'getFieldEntry'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/graphql/execute.lua:320: in function 'evaluateSelections'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/graphql/execute.lua:224: in function 'completeValue'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/graphql/execute.lua:178: in function 'getFieldEntry'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/graphql/execute.lua:320: in function 'evaluateSelections'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/graphql/execute.lua:224: in function 'getFieldEntry'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/graphql/execute.lua:320: in function 'evaluateSelections'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/graphql/execute.lua:224: in function 'completeValue'
cartridge.srv-1 |       ...
cartridge.srv-1 |       ./cartridge/graphql.lua:300: in function <./cartridge/graphql.lua:226>
cartridge.srv-1 |       [C]: in function 'xpcall'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/errors.lua:145: in function 'pcall'
cartridge.srv-1 |       ./cartridge/graphql.lua:335: in function 'sub'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/http/server.lua:658: in function </opt/cartridge/.rocks/share/tarantool/http/server.lua:636>
cartridge.srv-1 |       [C]: in function 'pcall'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/http/server.lua:736: in function 'process_client'
cartridge.srv-1 |       /opt/cartridge/.rocks/share/tarantool/http/server.lua:1199: in function </opt/cartridge/.rocks/share/tarantool/http/server.lua:1198>
cartridge.srv-1 |       [C]: in function 'pcall'
cartridge.srv-1 |       builtin/socket.lua:1060: in function <builtin/socket.lua:1058>
```

The bug is reproduced when a replica with medium id is removed from `box.space._cluster`. E.g. there are 2 instances and we expel the leader (switching it beforehand). It results in a gapped array `box.info.replication` and the graphql schema validation fails.

### PR DESCRIPTION
**Pull request by rosik**
There is a bug when a replica with medium id is removed from `box.space._cluster`. E.g. there are 2 instances and we expel the leader (switching it beforehand). It results in a gapped array `box.info.replication` and the GraphQL schema validation fails.

This patch makes the ReplicaStatus nullable in the GraphQL schema and fixes the response generation accordingly.

I didn't forget about

- [x] Tests
- [x] Changelog
- [x] Documentation (unnecessary)

Close #1283

### CODE REVIEW

**Review by rgbabaev — APPROVED** [review]

File: cartridge/lua-api/boxinfo.lua [hunk 1]
```diff
@@ -100,8 +100,9 @@ local function get_info(uri)
             }
         }
 
-        for i, replica in pairs(box_info.replication) do
-            ret.replication.replication_info[i] = {
+        for i = 1, box.space._cluster.index.primary:max().id do
```
Comment (olegrok) [inline cartridge/lua-api/boxinfo.lua:103]: why not `table.maxn(box_info.replication)`?

File: cartridge/webui/gql-boxinfo.lua [hunk 2]
```diff
@@ -195,7 +195,7 @@ local boxinfo_schema = {
                             ' replication log sequence numbers',
                     },
                     replication_info = {
-                        kind = gql_types.list(gql_replica_status.nonNull),
```
Comment (olegrok) [inline cartridge/webui/gql-boxinfo.lua:198]: To be precise it's not an array - actually it's a map where key is replica id, it's not abstract sparsed array

Comment (rosik) [reply cartridge/webui/gql-boxinfo.lua:198]: Does graphql have such type?

File: cartridge/lua-api/boxinfo.lua (hunk 1 above)
Comment (rosik) [reply cartridge/lua-api/boxinfo.lua]: I forgot about it. Fixed.

File: cartridge/webui/gql-boxinfo.lua (hunk 2 above)
Comment (olegrok) [reply cartridge/webui/gql-boxinfo.lua:198]: No, there is no "map" type. Maybe it should be `[{id: id, ...gql_replica_status}]`.
But ok, maybe we should preserve backward compatibility and stay it as is.

File: test/integration/expel_test.lua [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+end)
+
+function g.test_test()
+    local ret = g.A1.net_box:eval('return box.info.replication')
+    t.assert_covers(ret[1], {id = 1, uuid = g.r1_uuid}, ret)
+    t.assert_covers(ret[3], {id = 3, uuid = g.r3_uuid}, ret)
+    t.assert_equals(ret[2], nil, ret)
+
+    local ret = g.A1:graphql({
+        query = [[{ servers(uuid: "]] .. g.r3_uuid .. [[") { boxinfo {
```
Comment (olegrok) [inline test/integration/expel_test.lua:59]: May be it's better to user variables here.

File: test/integration/expel_test.lua [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+        [2] = box.NULL,
+        [3] = {
+            id = 3,
+            upstream_peer = box.NULL,
+            upstream_status = box.NULL,
+            downstream_status = box.NULL,
+        },
+    })
+
+    require('fiber').sleep(100)
```
Comment (olegrok) [inline test/integration/expel_test.lua:85]: Is it really needed?

File: test/integration/expel_test.lua (hunk 3 above)
Comment (rosik) [reply test/integration/expel_test.lua]: Fixed

File: test/integration/expel_test.lua (hunk 4 above)
Comment (rosik) [reply test/integration/expel_test.lua]: Damn, fixed

**Review by olegrok — APPROVED** [review]
