### PR TITLE
Adjust tests for tarantool >2.8

### LINKED ISSUE #1525: Fix flaky expel_test
Fix flaky expel_test. Recent encounter is [here](https://github.com/tarantool/cartridge/runs/3287257464?check_suite_focus=true)
```
integration.expel.test_api
...work/cartridge/cartridge/test/integration/expel_test.lua:73: expected: 
{
    {
        downstream_status = "follow",
        id = 1,
        upstream_peer = "admin@localhost:13301",
        upstream_status = "follow",
    },
    cdata<void *>: NULL,
    {
        downstream_status = cdata<void *>: NULL,
        id = 3,
        upstream_peer = cdata<void *>: NULL,
        upstream_status = cdata<void *>: NULL,
    },
}
actual: 
{
    {
        downstream_status = "follow",
        id = 1,
        upstream_peer = "admin@localhost:13301",
        upstream_status = "loading",
    },
    {
        downstream_status = "stopped",
        id = 2,
        upstream_peer = cdata<void *>: NULL,
        upstream_status = cdata<void *>: NULL,
            },
    {
        downstream_status = cdata<void *>: NULL,
        id = 3,
        upstream_peer = cdata<void *>: NULL,
        upstream_status = cdata<void *>: NULL,
    },
}
stack traceback:
	...work/cartridge/cartridge/test/integration/expel_test.lua:73: in function 'integration.expel.test_api'
	...
	[C]: in function 'xpcall'

Captured stdout:
A-2 | 2021-08-10 04:10:39.662 [6387] main/140/main I> subscribed replica a6027e63-d462-49ae-8c55-61e0cfbf599b at fd 435, aka 127.0.0.1:13302, peer of 127.0.0.1:38296
A-2 | 2021-08-10 04:10:39.662 [6387] main/140/main I> remote vclock {1: 5, 2: 1, 3: 1} local vclock {1: 4, 2: 1, 3: 1}
A-2 | 2021-08-10 04:10:39.663 [6387] relay/127.0.0.1:38296/101/main I> recover from `/tmp/tmp.cartridge.5tqFBoF0Y_nc/localhost-13302/00000000000000000004.xlog'
A-1 | 2021-08-10 04:10:39.660 [6379] main/129/main I> Backup of active config created: "/tmp/tmp.cartridge.5tqFBoF0Y_nc/localhost-13301/config.backup"
A-1 | 2021-08-10 04:10:39.660 [6379] relay/127.0.0.1:60016/101/main coio.cc:379 !> SystemError unexpected EOF when reading from socket, called on fd 448, aka 127.0.0.1:13301, peer of 127.0.0.1:60016: Broken pipe
A-1 | 2021-08-10 04:10:39.660 [6379] relay/127.0.0.1:60016/101/main C> exiting the relay loop
A-1 | 2021-08-10 04:10:39.660 [6379] main/129/main I> Instance state changed: RolesConfigured -> ConfiguringRoles
A-1 | 2021-08-10 04:10:39.661 [6379] main/129/main I> connecting to 2 replicas
A-1 | 2021-08-10 04:10:39.661 [6379] main/129/main C> failed to connect to 2 out of 2 replicas
A-1 | 2021-08-10 04:10:39.661 [6379] main/129/main C> leaving orphan mode
A-1 | 2021-08-10 04:10:39.661 [6379] main/129/main I> set 'replication' configuration option to ["admin@localhost:13301","admin@localhost:13302"]
A-1 | 2021-08-10 04:10:39.661 [6379] main I> removed replica e237a6eb-fe43-48bb-90c1-e0468decc27b
A-1 | 2021-08-10 04:10:39.662 [6379] main/129/main I> Failover disabled
A-1 | 2021-08-10 04:10:39.662 [6379] main/129/main I> --- apply_config({is_master = true})
A-1 | 2021-08-10 04:10:39.662 [6379] main/129/main I> Roles configuration finished
A-1 | 2021-08-10 04:10:39.662 [6379] main/129/main I> Instance state changed: ConfiguringRoles -> RolesConfigured
A-1 | 2021-08-10 04:10:39.662 [6379] main/147/main twophase.lua:428 W> Committed patch_clusterwide at localhost:13301
A-1 | 2021-08-10 04:10:39.662 [6379] main/147/main twophase.lua:428 W> Committed patch_clusterwide at localhost:13302
A-1 | 2021-08-10 04:10:39.662 [6379] main/147/main twophase.lua:573 W> Clusterwide config updated successfully
A-1 | 2021-08-10 04:10:39.662 [6379] main/160/applier/admin@localhost:13302 I> remote master 7ecd7ed2-dd91-4111-8490-1876089bfd93 at 127.0.0.1:13302 running Tarantool 2.8.1
A-1 | 2021-08-10 04:10:39.662 [6379] main/161/applier/admin@localhost:13301 I> remote master a6027e63-d462-49ae-8c55-61e0cfbf599b at 127.0.0.1:13301 running Tarantool 2.8.1
A-1 | 2021-08-10 04:10:39.662 [6379] main/161/applier/admin@localhost:13301 C> leaving orphan mode
A-1 | 2021-08-10 04:10:39.662 [6379] main/160/applier/admin@localhost:13302 I> authenticated
A-1 | 2021-08-10 04:10:39.663 [6379] main/160/applier/admin@localhost:13302 I> subscribed
A-1 | 2021-08-10 04:10:39.663 [6379] main/160/applier/admin@localhost:13302 I> remote vclock {1: 4, 2: 1, 3: 1} local vclock {1: 5, 2: 1, 3: 1}
A-1 | 2021-08-10 04:10:39.663 [6379] main/160/applier/admin@localhost:13302 I> RAFT: message {term: 1, state: follower} from 3
A-1 | 2021-08-10 04:10:39.663 [6379] main/162/applierw/admin@localhost:13302 C> leaving orphan mode
```

### LINKED ISSUE #1526: Adapt nightly tests to tarantool >2.8
Currently nightly tests for tarantool 2.8 and 2.9 are red. Mostly because of changed "duplicate key" message. It doesn't affect any logic and can be fixed by taking into account tarantool version.

Affected tests:
- `integration/issues_test.lua`
- `integration/stateboard_test.lua`

### PR DESCRIPTION
**Pull request by Steap2448**
Take into account the tarantool version when asserting the "duplicate key" message (it's changed since 2.8).

Also, fix flaky `expel_test`.

I didn't forget about

- [x] Tests
- [x] ~~Changelog~~
- [x] ~~Documentation~~

Close #1526
Close #1525

### CODE REVIEW

File: test/integration/issues_test.lua [hunk 1]
```diff
@@ -111,18 +113,34 @@ function g.test_broken_replica()
     ]])
 
     local function issue_fmt(from, to)
-        return {
-            level = 'critical',
-            topic = 'replication',
-            replicaset_uuid = g.cluster:server(to).replicaset_uuid,
-            instance_uuid = g.cluster:server(to).instance_uuid,
+        local message
+        if tarantool_version > '2.8' then
```
Comment (rosik) [inline test/integration/issues_test.lua:117]: This is a time bomb:

```
tarantool> "2.8.1" > "2.8"
---
- true
...

tarantool> "2.9" > "2.8"
---
- true
...

tarantool> "2.10" > "2.8"
---
- false
...
```

Also, should it be `>=`?

Comment (Steap2448) [reply test/integration/issues_test.lua]: defused

**Review by rosik — APPROVED** [review]
