### PR TITLE
Fix GraphQL query `auth_params.username`

### LINKED ISSUE #1633: [2pt] Make field "Full name" obligatory on the form "Add a new user"
To prevent situation when authorized user is working with empty value in the right top corner

image

### PR DESCRIPTION
**Pull request by usenko-timur**
* Fix GraphQL query ``auth_params.username`` returns empty string instead of ``username``.

- [x] Tests
- [x] Changelog
- [x] Documentation

Close #1633

### CODE REVIEW

**Review by yngvar-antonsson — APPROVED** [review]

File: cartridge/webui/api-auth.lua [hunk 1]
```diff
@@ -76,7 +76,7 @@ local function get_auth_params()
 
     local username = auth.get_session_username()
     local user = username and auth.get_user(username)
-    if user ~= nil and user.fullname ~= nil then
+    if user and (user.fullname or '') ~= '' then
```
Comment (olegrok) [inline cartridge/webui/api-auth.lua:79]: This check is quite strange.
  - Check will be broken if fullname is box.NULL
  - And seems it's easier to check that string length has non-zero length: `user ~= nil and user.fullname ~= nil and #user.fullname > 0`

Comment (usenko-timur) [reply cartridge/webui/api-auth.lua]: Thanks, fixed!

**Review by olegrok — APPROVED** [review]

**Review by OlgaYakovleva — APPROVED** [review]
Verified on cartridge as on TDG2 there is not filed "full name"
