### PR TITLE
Fix failover_promote when vclockkeeper ordinal changed

### LINKED ISSUE #1399: `failover_promote` returns an error via `force_inconsistency: true`
## Bug description

`failover_promote` returns an error via `force_inconsistency: true`. Reproduced in both stateboard cases (tarantool and etcd).
Vclockkeeper value in stateboard storage was changed between `get_vclockkeeper` and `set_vclockkeeper` calls in the `force_inconsistency` function. 
That check should be on the server (stateboard or etcd), not the client.
https://github.com/tarantool/cartridge/blob/514262440e6bd3f69b584b8d64f818722cd0272a/cartridge/stateboard-client.lua#L113-L118

Needs extra investigation to fix etcd error. 

## Steps to reproduce

<details>
1. The cluster with simple topology is deployed:

```yaml
    core_1_replicaset:
      hosts:
        core-1:
      vars:
        replicaset_alias: core-1
        roles:
          - vshard-router
          - failover-coordinator

    storage_1_replicaset:
      hosts:
        storage-1-leader:
        storage-1-replica:
        storage-1-replica-2:
      vars:
        replicaset_alias: storage-1
        failover_priority:
          - storage-1-leader
          - storage-1-replica-2
          - storage-1-replica
        roles:
          - vshard-storage

    storage_2_replicaset:
      hosts:
        storage-2-leader:
        storage-2-replica:
      vars:
        replicaset_alias: storage-2
        failover_priority:
          - storage-2-leader
          - storage-2-replica
        roles:
          - vshard-storage
```

The failover is set to

```yaml
    cartridge_failover_params:
      mode: stateful
      state_provider: stateboard
      stateboard_params:
        uri: vm1:4001
        password: secret-stateboard
```

2. Leaders are promoted to `storage-1-replica` and `storage-2-replica` with `force_inconsistency: false`.
3. Leaders are promoted to  `core-1`, `storage-1`, `storage-2` with `force_inconsistency: true`.

On step 3 the error is returned: `Failed to promote leaders: Promotion succeeded, but inconsistency wasn't forced: Ordinal comparison failed (requested 5, current 7)`.

</details>

1) use test from https://github.com/tarantool/cartridge/pull/1710
2) add fiber.sleep before https://github.com/tarantool/cartridge/blob/869a2bd381cf7af5ae6959ae07a41318f3e6585a/cartridge/stateboard-client.lua#L122
3) Profit

## Actual behavior

`Promotion succeeded, but inconsistency wasn't forced: Compare failed (101): [223 != 253]`
https://github.com/tarantool/cartridge/blob/869a2bd381cf7af5ae6959ae07a41318f3e6585a/cartridge/etcd2-client.lua#L219

`Promotion succeeded, but inconsistency wasn't forced: Ordinal comparison failed (requested 5, current 7)`
https://github.com/tarantool/cartridge/blob/869a2bd381cf7af5ae6959ae07a41318f3e6585a/cartridge/stateboard-client.lua#L122

## Expected behavior

No error returned.

### PR DESCRIPTION
**Pull request by yngvar-antonsson**
I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation

Close #1399

### CODE REVIEW

File: cartridge/stateboard.lua [hunk 1]
```diff
@@ -155,6 +155,12 @@ local function set_vclockkeeper_impl(replicaset_uuid, instance_uuid, ordinal, vc
 
     local vclockkeeper = box.space.vclockkeeper:get({replicaset_uuid})
     if ordinal ~= (vclockkeeper and vclockkeeper.ordinal) then
+        if vclockkeeper.instance_uuid == instance_uuid
+        and vclock == nil
+        then
+            -- No update needed
+            return true
+        end
```
Comment (filonenko-mikhail) [inline cartridge/stateboard.lua:163]: i think more beautiful to keep this `if` branch separate with additional cond `ordinal ~= (vclockkeeper and vclockkeeper.ordinal)`

**Review by filonenko-mikhail — APPROVED** [review]
