### PR TITLE
Fix remote-control test for Tarantool 2.4+

### LINKED ISSUE #1058: [1pt] Fix remote_control_test for tarantool 2.4+
Tarantool box.error API was significantly refactored in scope of https://github.com/tarantool/tarantool/issues/4398 and now cartridge tests fail:

```lua
local ok, err = pcall(conn.eval, conn,
    'error("ScriptError", 0)'
)
t.assert_not(ok)
t.assert_equals(type(err), 'cdata')
t.assert_equals(err.code, box.error.PROC_LUA) -- expected: 32, actual: nil
```

https://gitlab.com/tarantool/cartridge/-/jobs/746467482

### PR DESCRIPTION
**Pull request by Steap2448**
Up to Tarantool 2.4 errors that come through net.box were treated as ClientError. However, since 2.4 they pass through net.box transparently preserving their error type but not the error code. That being said, remote-control behave similarly to the older versions of Tarantool and provide error codes even if there are missing. So, tests were actualized for both versions of `box.error`.

I didn't forget about

- [x] Tests
- [ ] Changelog
- [ ] Documentation

Close #1058

### CODE REVIEW

File: test/unit/remote_control_test.lua [hunk 1]
```diff
@@ -530,9 +530,19 @@ function g.test_call()
         )
         t.assert_not(ok)
         t.assert_equals(type(err), 'cdata')
-        t.assert_equals(err.code, box.error.PROC_LUA)
         t.assert_equals(err.message, 'ScriptError')
 
+        -- Up to Tarantool 2.4 errors that come through net.box were
```
Comment (olegrok) [inline test/unit/remote_control_test.lua:535]: Considering this comment https://github.com/tarantool/cartridge/issues/1058#issuecomment-699948095, I think it's better to remove lines that's not compatible with newest Tarantool versions. (It's a reason why I changed my opinion https://github.com/tarantool/cartridge/pull/1059#discussion_r494579391)

I think it's not useful to test that some tests don't fail on Tarantool **before** 2.4.

Comment (Steap2448) [reply test/unit/remote_control_test.lua]: Done

**Comment by olegrok** [comment]
LGTM

Maybe it could be valuable to add to comments that we still preserve netbox error contracts. Because old behaviour wasn't properly documented. (according https://github.com/tarantool/cartridge/issues/1058#issuecomment-699948095)

**Review by olegrok — APPROVED** [review]

**Review by rosik — APPROVED** [review]
