### PR TITLE
issue1852 fix replication_synchro_quorum

### LINKED ISSUE #1852: TypeCastError: invalid configuration parameter replication_synchro_quorum (string|number expected, got number)
I'm using Cartridge 2.7.4 + Tarantool 2.8.3.

Steps to reproduce:

1. `cartridge create; cartridge build`

2. Add `replication_synchro_quorum: 2` into `instances.yaml`

3. `cartridge start`

```console
$ cartridge start router
myapp.router | LuajitError: /tmp/tmp.bFfJgzuMxo/myapp/init.lua:43: TypeCastError: invalid configuration parameter replication_synchro_quorum (string|number expected, got number)
myapp.router | stack traceback:
myapp.router |  ...uMxo/myapp/.rocks/share/tarantool/cartridge/argparse.lua:487: in function 'get_box_opts'
myapp.router |  ...mp.bFfJgzuMxo/myapp/.rocks/share/tarantool/cartridge.lua:321: in function 'cfg'
myapp.router |  /tmp/tmp.bFfJgzuMxo/myapp/init.lua:34: in main chunk
myapp.router | fatal error, exiting the event loop
   • myapp.router... EXITED
   ⨯ myapp.router: Process exited: Exited unsuccessfully: exit status 1
   ⨯ All instances exited     

```

### PR DESCRIPTION
**Pull request by panticonur**
Fix replication_synchro_quorum param.

I didn't forget about

- [x] Changelog
- [x] Test

Close #1852

### CODE REVIEW

**Comment by yngvar-antonsson** [comment]
Please add test

File: cartridge/argparse.lua [hunk 1]
```diff
@@ -445,7 +445,7 @@ local function get_opts(opts)
             -- ignore
         elseif type(value) == opttype then
             ret[optname] = value
-        elseif type(value) == 'number' and opttype == 'string' then
+        elseif type(value) == 'number' and (opttype == 'string' or opttype == 'string|number' ) then
```
Comment (yngvar-antonsson) [inline cartridge/argparse.lua:448]: Please add test

**Review by yngvar-antonsson — CHANGES_REQUESTED** [review]

File: cartridge/argparse.lua (hunk 1 above)
Comment (olegrok) [reply cartridge/argparse.lua:448]: I guess using `string|number` is a bit incorrect. It easily could be `number|string` and it should be handled in the same way.

Comment (olegrok) [reply cartridge/argparse.lua:448]: Здесь не нужна перестановка. Я говорю, что вижу здесь захардкоженную проверку, говорю, что optype может быть и 'number|string'. В этом случае проверка также должна срабатывать, но не будет.

Comment (panticonur) [reply cartridge/argparse.lua:448]: Понял, ты прав про харкод.

File: cartridge/argparse.lua [hunk 2]
```diff
@@ -440,46 +440,59 @@ local function get_opts(opts)
 
     local ret = {}
     for optname, opttype in pairs(opts) do
+        local opttype_str = false
+        local opttype_num = false
+        local opttype_bool = false
+        local multi_types = string.gsub(opttype, ' ', '')
+        for _opttype in string.gmatch(multi_types, "[^|]+") do
```
Comment (olegrok) [inline cartridge/argparse.lua:447]: I suggest to use string.split('|') instead.

File: cartridge/argparse.lua [hunk 3]
```diff
@@ -440,46 +440,59 @@ local function get_opts(opts)
...
+
         local value = args[optname]
         if value == nil then -- luacheck: ignore 542
             -- ignore
         elseif type(value) == opttype then
             ret[optname] = value
-        elseif type(value) == 'number' and opttype == 'string' then
-            ret[optname] = tostring(value)
+        elseif type(value) == 'number' and ( opttype_num or opttype_str ) then
+            local _value = tostring(value)
```
[the remark this answers is not in the document]
Comment (panticonur) [reply cartridge/argparse.lua:468]: I think there it can be just an number. But some tests will be fail.
```
/Users/andrei.sidorov/cartridge/test/unit/argparse_test.lua:331: expected: 
{
    listen = "13301",
}
actual: 
{
    listen = 13301,
}
```

[the remark this answers is not in the document]
Comment (olegrok) [reply cartridge/argparse.lua:468]: Here we could simply fix a test.
I guess 13301 (as number) is valid value for listening.

File: cartridge/argparse.lua [hunk 4]
```diff
@@ -440,46 +440,59 @@ local function get_opts(opts)
 
     local ret = {}
     for optname, opttype in pairs(opts) do
+        local opttype_str = false
+        local opttype_num = false
+        local opttype_bool = false
+        local multi_types = string.gsub(opttype, ' ', '')
```
[the remark this answers is not in the document]
Comment (panticonur) [reply cartridge/argparse.lua:446]: Lua does not have a split function in its standard library.
http://lua-users.org/wiki/SplitJoin

File: cartridge/argparse.lua (hunk 3 above)
[the remark this answers is not in the document]
Comment (olegrok) [reply cartridge/argparse.lua:468]: Replace listen to string|number then.
Tarantool accepts numeric listen - https://github.com/tarantool/tarantool/blob/4e9a94a38c381cefc71ae53ca9a959bcdcf6434b/src/box/lua/load_cfg.lua#L167

File: test/unit/argparse_test.lua [hunk 5]
```diff
@@ -392,6 +392,21 @@ g.test_replication_quorum_opts = function()
         replication_synchro_quorum = 'N/3+5',
     })
 
+    utils.file_write(
```
Comment (olegrok) [inline test/unit/argparse_test.lua:395]: Is it possible to add some custom parameter e.g. "number|boolean" and check that it's also parsed correctly?

**Review by olegrok — APPROVED** [review]

File: cartridge/argparse.lua [hunk 6]
```diff
@@ -194,6 +194,7 @@ local box_opts = {
     election_mode            = 'string', -- **string**
     election_timeout         = 'number', -- **number**
     election_fencing_enabled = 'boolean', -- **boolean**
+    testing_number_boolean   = 'number|boolean', -- **number|boolean**
```
Comment (olegrok) [inline cartridge/argparse.lua:197]: No, please don't mix box options with some test values.

AFAIK there is a way to add some custom options to argparse without doing that. Or you can export this table somehow and modify in your test.

**Review by olegrok — CHANGES_REQUESTED** [review]

**Review by olegrok — APPROVED** [review]

**Review by yngvar-antonsson — APPROVED** [review]
