### PR TITLE
Make clusterwide config upload a separate stage

### LINKED ISSUE #1145: [2pt] Uploading big config fails on large clusters
When the cluster-wide configuration is updated, Cartridge sends it whole to every instance in a cluster. He does it in parallel and imposes a hardcoded 5-second timeout restriction. If we suppose that there are 100 instances, the size of config is 1MB and the network bandwidth is 100Mb/s, then it would take 8 seconds and obviously fail.

### PR DESCRIPTION
**Pull request by Steap2448**
For historical reasons, there were two issues in the `patch_clusterwide` logics:

1. The 5-second timeout for all communications was hardcoded.
2. No optimizations were undertaken there, it was was suboptimal and wasteful.

It was OK when the config was small and there were only a few instances in the cluster, but it's a problem for big installations nowadays.

This patch introduces a new `patch_clusterwide` stage - upload (consolidated in a separate module). It spreads the data across instances in a network-efficient manner.

Also in this patch:

- Change `issues_test.lua` and remove unnecessary checks from cypress `sigstop.spec.js` because the SIGStOP doesn't result in config lock and mismatch anymore.

I didn't forget about

- [x] Tests
- [x] Changelog
- [x] Documentation

Close #1145

### CODE REVIEW

**Review by HustonMmmavr — APPROVED** [review]

File: cartridge/upload.lua [hunk 1]
```diff
@@ -0,0 +1,313 @@
...
+local function upload_begin(upload_id)
+    checks('string')
+
+    vars.upload_fibers[upload_id] = fiber.self()
+
+    local upload_path = vars.get_upload_path(upload_id)
+    local ok, err = utils.mktree(fio.dirname(upload_path))
+    fiber.testcancel()
+    if ok == nil then
+        return nil, err
```
Comment (rosik) [inline cartridge/upload.lua:65]: cleanup vars.upload_fibers

File: cartridge/upload.lua [hunk 2]
```diff
@@ -0,0 +1,313 @@
...
+
+_G.__cartridge_upload_begin = function(...) return errors.pcall('E', upload_begin, ...) end
+_G.__cartridge_upload_transmit = function(...) return errors.pcall('E', upload_transmit, ...) end
+_G.__cartridge_upload_finish = function(...) return errors.pcall('E', upload_finish, ...) end
+_G.__cartridge_upload_cleanup = function(...) return errors.pcall('E', upload_cleanup, ...) end
+
+return {
+    upload = upload,
+    inbox = vars.inbox,
+    _options = vars.options,
```
Comment (rosik) [inline cartridge/upload.lua:312]: Rename, make configurable via argparse

File: cartridge/upload.lua [hunk 3]
```diff
@@ -0,0 +1,313 @@
...
+--
+-- @param data
+--   any Lua object.
+-- @tparam {string,...} uri_list
+--   array of URIs.
+--
+-- @treturn[1] string `upload_id` (if at least one upload succeded)
+-- @treturn[2] nil
+-- @treturn[2] table Error description
+local function upload(data, uri_list)
```
Comment (olegrok) [inline cartridge/upload.lua:193]: This module is quite atomic and can be used by other projects, let's move timeout to options

Comment (olegrok) [reply cartridge/upload.lua:193]: `upload_path ` also should be moved to options. I think all constants/options could be passed via arguments.
Cartridge should provide only default values and do it out of the scope this module.

File: cartridge/upload.lua [hunk 4]
```diff
@@ -0,0 +1,313 @@
...
+local utils = require('cartridge.utils')
+
+local vars = require('cartridge.vars').new('cartridge.upload')
+
+local UploadError = errors.new_class('UploadError')
+
+--- The uploaded data.
+-- `{[upload_id] = data}`
+-- @table inbox
+vars:new('inbox', {})
```
Comment (olegrok) [inline cartridge/upload.lua:26]: It could be managed externally. Maybe as a Tarantool future.
`upload` could result some object that has some condition. We could wait result, interrupt uploading, etc via such object.
Also it should be user responsibility how to manage result of upload. And it solves a problem when in case of failure we store garbage on filesystem - `__gc` metamethod or `cleanup` callback should remove this garbage.

File: cartridge/upload.lua (hunk 3 above)
Comment (rosik) [reply cartridge/upload.lua]: > This module is quite atomic and can be used by other projects, let's move timeout to options

Good idea. Done.



> `upload_path ` also should be moved to options. I think all constants/options could be passed via arguments.
> Cartridge should provide only default values and do it out of the scope this module.

And this seems to be impossible. The sending side can't know where the accepting side wants to store the data.

File: cartridge/upload.lua (hunk 4 above)
Comment (rosik) [reply cartridge/upload.lua:26]: It's a distributed system. The uploaded data can't be deleted before the sender makes another netbox call (`prepare_2pc`). The only thing I could do is a time-managed GC, but it's not a cure - overcomplicated and there still may be problems.

File: cartridge/upload.lua [hunk 5]
```diff
@@ -0,0 +1,322 @@
...
+-- others are the transmitters. The others wait patiently till the
+-- `upload_finish()`.
+local function upload_begin(upload_id)
+    checks('string')
+
+    vars.upload_fibers[upload_id] = fiber.self()
+
+    local upload_path = get_upload_path(upload_id)
+    local ok, err = utils.mktree(fio.dirname(upload_path))
+    fiber.testcancel()
```
Comment (olegrok) [inline cartridge/upload.lua:64]: `testcancel` raises. You won't perform `vars.upload_fibers[upload_id] = nil` if this function raises an error.

File: cartridge/upload.lua [hunk 6]
```diff
@@ -0,0 +1,322 @@
...
+-- during the `upload_finish()` step.
+local function upload_transmit(upload_id, payload)
+    checks('string', 'string')
+
+    vars.upload_fibers[upload_id] = fiber.self()
+
+    local upload_path = get_upload_path(upload_id)
+    local payload_path = fio.pathjoin(upload_path, 'payload')
+    local ok, err = utils.file_write(payload_path, payload)
+    fiber.testcancel()
```
Comment (olegrok) [inline cartridge/upload.lua:100]: `testcancel` raises. You won't perform `vars.upload_fibers[upload_id] = nil` if this function raises an error.

File: cartridge/upload.lua [hunk 7]
```diff
@@ -0,0 +1,322 @@
...
+    if vars.upload_fibers[upload_id] ~= nil then
+        pcall(fiber.cancel, vars.upload_fibers[upload_id])
+        vars.upload_fibers[upload_id] = nil
+    end
+
+    local upload_path = get_upload_path(upload_id)
+    local random_path = utils.randomize_path(upload_path)
+
+    local ok = fio.rename(upload_path, random_path)
+    local _errno = errno()
```
Comment (olegrok) [inline cartridge/upload.lua:148]: It's redundant action to call errno here. It's not needed if ok is true.

File: cartridge/upload.lua [hunk 8]
```diff
@@ -0,0 +1,322 @@
...
+                'Error removing %s: %s',
+                upload_path, errno.strerror(_errno)
+            )
+            return false
+        end
+    end
+
+    local ok = fio.rmtree(random_path)
+    local _errno = errno()
+    if not ok then
```
Comment (olegrok) [inline cartridge/upload.lua:164]: It's redundant action to call errno here. It's not needed if ok is true.

File: cartridge/upload.lua [hunk 9]
```diff
@@ -0,0 +1,322 @@
...
+        return nil, _upload_error
+    end
+
+    return upload_id
+end
+
+_G.__cartridge_upload_begin = function(...) return errors.pcall('E', upload_begin, ...) end
+_G.__cartridge_upload_transmit = function(...) return errors.pcall('E', upload_transmit, ...) end
+_G.__cartridge_upload_finish = function(...) return errors.pcall('E', upload_finish, ...) end
+_G.__cartridge_upload_cleanup = function(...) return errors.pcall('E', upload_cleanup, ...) end
```
Comment (olegrok) [inline cartridge/upload.lua:314]: You don't actually need to pass `...` here because you exactly know a number of arguments - one upload_id.
varargs are bit slower than usual function call with determined number of arguments.

File: test/integration/upload_test.lua [hunk 10]
```diff
@@ -0,0 +1,161 @@
...
+        err = 'Timeout exceeded',
+    })
+
+    -- prefix should be cleaned up even if upload_begin fails
+    t.assert_equals(fio.listdir(g.upload_path_1), {})
+    t.assert_equals(fio.listdir(g.upload_path_2), {})
+
+    g.s2.process:kill('CONT')
+    -- give the instance some time to wake up after stop
+    fiber.sleep(0.3)
```
Comment (olegrok) [inline test/integration/upload_test.lua:75]: Could you replace it with some wait_for?

File: test/integration/upload_test.lua [hunk 11]
```diff
@@ -0,0 +1,161 @@
...
+        server_command = helpers.entrypoint('srv_basic'),
+        cookie = helpers.random_cookie(),
+        replicasets = {{
+            alias = 'main',
+            uuid = helpers.uuid('a'),
+            roles = {},
+            servers = {
+                -- first upload group: s1 and s2
+                {env = {TARANTOOL_UPLOAD_PREFIX = g.upload_path_1}},
+                {env = {TARANTOOL_UPLOAD_PREFIX = g.upload_path_1}},
```
Comment (olegrok) [inline test/integration/upload_test.lua:25]: Maybe it's reasonable to increase number of servers up to 5 or even more. In case of problems with concurrency and shared resource problems we have more chances to catch a problem in CI.

File: cartridge/upload.lua (hunk 5 above)
Comment (rosik) [reply cartridge/upload.lua:64]: It's ok. In this case the `upload_fibers` will be cleaned by the `cleanup` stage which cancelled the fiber.

Comment (olegrok) [reply cartridge/upload.lua:64]: Ok, but it's not so obvious, please add a comment.

Comment (olegrok) [reply cartridge/upload.lua:64]: However, in fact we can't guarantee that cleanup stage will be executed someday in case of temporary problems with network.

File: cartridge/upload.lua (hunk 7 above)
Comment (rosik) [reply cartridge/upload.lua]: The main danger of errno is that it may be overridden by some other consequent fio operation. I've changed this place, but in another way.

File: test/integration/upload_test.lua (hunk 10 above)
Comment (rosik) [reply test/integration/upload_test.lua:75]: I was going to, but the predicate turned out to be super complicated. I need to wait when another async non-atomic (yielding) netbox call finishes on the server-side. I've decided that sleep is the shortest way. If the test turns out to be flaky I'll fix it later, but today it seems to be ok.

File: cartridge/upload.lua (hunk 5 above)
Comment (rosik) [reply cartridge/upload.lua:64]: > Ok, but it's not so obvious, please add a comment.

Done

> However, in fact we can't guarantee that cleanup stage will be executed someday in case of temporary problems with network.

The necessity of persisting `upload_fibers` is to avoid a race between `begin` and `cleanup`. The necessity of cleaning up the `upload_fibers` is to avoid canceling an innocent fiber that belongs to the iproto fiber pool and has already been reused by that time.

File: cartridge/upload.lua (hunk 7 above)
Comment (olegrok) [reply cartridge/upload.lua]:
```lua
local _errno
local ok, err = fio.some_operation()
if not ok then
   _errno = errno()
end
```

No redefinition, to excess actions.

File: test/integration/upload_test.lua (hunk 10 above)
Comment (olegrok) [reply test/integration/upload_test.lua:75]: ok

File: cartridge/upload.lua (hunk 5 above)
Comment (rosik) [reply cartridge/upload.lua:64]: To sum up, if the cleanup stage wasn't called for some reason, the garbage will remain in `/tmp` and in lua context. And it's ok for now.

File: cartridge/upload.lua (hunk 9 above)
Comment (rosik) [reply cartridge/upload.lua:311]: I'm ok to sacrifice that performance for the sake of code brevity. Hope it's not too much.

**Review by olegrok — APPROVED** [review]

**Review by rosik — APPROVED** [review]
