### PR TITLE
Fix CI for tarantool 2.4+

### LINKED ISSUE #1058: [1pt] Fix remote_control_test for tarantool 2.4+
Tarantool box.error API was significantly refactored in scope of https://github.com/tarantool/tarantool/issues/4398 and now cartridge tests fail:

```lua
local ok, err = pcall(conn.eval, conn,
    'error("ScriptError", 0)'
)
t.assert_not(ok)
t.assert_equals(type(err), 'cdata')
t.assert_equals(err.code, box.error.PROC_LUA) -- expected: 32, actual: nil
```

https://gitlab.com/tarantool/cartridge/-/jobs/746467482

### PR DESCRIPTION
**Pull request by rosik**
CI for Tarantool 2.6 [fails](https://gitlab.com/tarantool/cartridge/-/jobs/754399625) for two reasons:

1. Errors API was significantly refactored in scope of https://github.com/tarantool/tarantool/issues/4398.

2. Recently in [1] we've monkey-patched `fio.tempdir` implementation because it didn't respect `$TMPDIR` env variable. In [2] we've extended it with `base` agrument because etcd required another temp directory (`/dev/shm` tmpfs in Gitlab CI runner wasn't large enough).  Later, TMPDIR was supported in tarantool (see [3]), but it still doesn't support passing `base` as an argument.

This patch fixes the second problem only - it completely eliminates the use of built-in `fio.tempdir` implementation in favor of ours.
The first one will be fixed separately (maybe in tarantool)

[1] https://github.com/tarantool/cartridge/pull/613
[2] https://github.com/tarantool/cartridge/pull/966
[3] https://github.com/tarantool/tarantool/issues/4794

I didn't forget about

- [x] Tests
- [x] Changelog (unnecessary)
- [x] Documentation (unnecessary)

Part of #1058

### CODE REVIEW

File: test/unit/remote_control_test.lua [hunk 1]
```diff
@@ -530,7 +530,6 @@ function g.test_call()
         )
         t.assert_not(ok)
         t.assert_equals(type(err), 'cdata')
-        t.assert_equals(err.code, box.error.PROC_LUA)
```
Comment (olegrok) [inline test/unit/remote_control_test.lua:533]: This way you just remove a part of tests. IMO it's not a solution. I think it's appropriate to support test cases for all versions based on _TARANTOOL value.

Personally, I'm not sure we should avoid tarantool internals consideration. Especially in case when implement Tarantool-compatible interfaces.

**Review by olegrok — APPROVED** [review]
