### PR TITLE
Fix get_enabled_roles to work w/o args

### LINKED ISSUE #1396: `get_enabled_roles` misbehaviour
```
> cartridge_roles.get_enabled_roles()
---
- []
...

> cartridge_roles.get_enabled_roles({})
---
- metrics: true
...
```

### PR DESCRIPTION
**Pull request by yngvar-antonsson**
I didn't forget about

- [x] Tests
- [x] Changelog
- [x] Documentation

Close #1396

### CODE REVIEW

File: test/integration/roles_test.lua [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+        return roles.get_enabled_roles({myrole = true})
+    ]])
+
+    t.assert_equals(roles_list, {
+        ['ddl-manager'] = true,
+        ['myrole-permanent'] = true,
+        ['myrole'] = true,
+        ['myrole-hidden'] = true,
+        ['myrole-dependency'] = true,
+    })
```
Comment (rosik) [inline test/integration/roles_test.lua:66]: better extend existing `test/unit/roledeps_test.lua`

**Review by rosik — CHANGES_REQUESTED** [review]

**Review by rosik — APPROVED** [review]
