### PR TITLE
Accept remote-control connections in InitError state

### LINKED ISSUE #1286: [2pt] Investigate misterious "Connection timed out" error
On brand new Cartridge 2.4.0 role validate_config fails if config is invalid due to config error leads an NetboxConnectionError with ConnectionTimeout while on 2.3.0 it returns meaningfull GraphQL error.

Steps to reproduce:
1. Setup new app with metrics 0.7.0
2. Run it
3. Go to Code section and create metrics.yml with valid yaml but some spell error in format
4. Press Apply

On Cartridge 2.3 you will get:
image

On Cartridge 2.4 you will get:
image

### PR DESCRIPTION
**Pull request by Steap2448**
Remote control is accepting connections even if instance enters ``InitError`` state.

I didn't forget about

- [x] Tests
- [x] Changelog
- [x] Documentation

Close #1286

### CODE REVIEW

File: test/integration/state_machine_test.lua [hunk 1]
```diff
@@ -710,3 +710,22 @@ function g.test_prepare_state_error()
...
+function g.test_init_error_remote_control()
+    -- Even if instance enters InitError state
+    -- remote-control should accept connections
+    g.cluster:stop()
+
+    local fio = require('fio')
+    local config = fio.pathjoin(g.cluster.datadir, 'localhost-13301', 'config')
+    local topology = fio.open(fio.pathjoin(config, 'topology.yml'), {'O_WRONLY'})
+    topology:write('42')
+    topology:close()
```
Comment (rosik) [inline test/integration/state_machine_test.lua:723]: `utils.file_write`?

File: test/integration/state_machine_test.lua [hunk 2]
```diff
@@ -710,3 +710,22 @@ function g.test_prepare_state_error()
...
+    g.master:start()
+
+    helpers.wish_state(g.master, 'InitError')
+
+    local conn = require('net.box').connect('localhost:13301')
```
Comment (rosik) [inline test/integration/state_machine_test.lua:728]: I'd suggest trying calling `patch_clusterwide` and checking its error message. It'll make the intention more clear.

Comment (rosik) [reply test/integration/state_machine_test.lua:728]: Btw the connection state is already checked by `helpers.wish_state` implicitly.

**Review by rosik — CHANGES_REQUESTED** [review]

**Review by rosik — APPROVED** [review]
