### PR TITLE
Fix flaky tests

### LINKED ISSUE #1530: Fix flaky api_query_test
Recently encountered in nightly tests on tarantool 2.7.2-186-g1174d64c1. [Logs](https://github.com/tarantool/cartridge/runs/3336589404?check_suite_focus=true).

```
Failed tests:
-------------

1) integration.api_query.test_suggestions
.../cartridge/cartridge/test/integration/api_query_test.lua:196: expected: 
{
    disable_servers = cdata<void *>: NULL,
    force_apply = cdata<void *>: NULL,
    refine_uri = cdata<void *>: NULL,
    restart_replication = cdata<void *>: NULL,
}
actual: 
{
    disable_servers = cdata<void *>: NULL,
    force_apply = cdata<void *>: NULL,
    refine_uri = cdata<void *>: NULL,
    restart_replication = {{uuid = "bbbbbbbb-bbbb-0000-0000-000000000001"}},
}
stack traceback:
	.../cartridge/cartridge/test/integration/api_query_test.lua:196: in function 'integration.api_query.test_suggestions'
	...
	[C]: in function 'xpcall'

Ran 363 tests in 313.975 seconds, 362 successes, 1 fail, 1 skipped
```

I guess it's related to https://github.com/tarantool/tarantool/issues/4669

### LINKED ISSUE #1552: Fix flaky integration.restart_replication.test_suggestion
```log

Failed tests:
-------------

1) integration.restart_replication.test_suggestion
.../cartridge/test/integration/restart_replication_test.lua:55: expected: 
{
    {
        instance_uuid = "3a29e0fe-ab66-4274-a071-7006ad982ffb",
        level = "critical",
        message = "Replication from localhost:13302 (A-2) to localhost:13301 (A-1) isn't running",
        replicaset_uuid = "b715a5e9-7602-48d2-adc2-e77bbdba4633",
        topic = "replication",
    },
}
actual: 
{
    {
        instance_uuid = "c877621e-73f7-4703-9f25-00040617079e",
        level = "warning",
        message = "Replication from localhost:13301 (A-1) to localhost:13302 (A-2): long idle (2.1 > 1)",
        replicaset_uuid = "b715a5e9-7602-48d2-adc2-e77bbdba4633",
        topic = "replication",
    },
    {
        instance_uuid = "3a29e0fe-ab66-4274-a071-7006ad982ffb",
        level = "critical",
        message = "Replication from localhost:13302 (A-2) to localhost:13301 (A-1) isn't running",
        replicaset_uuid = "b715a5e9-7602-48d2-adc2-e77bbdba4633",
        topic = "replication",
    },
}
stack traceback:
	.../cartridge/test/integration/restart_replication_test.lua:55: in function 'integration.restart_replication.test_suggestion'
	...
	[C]: in function 'xpcall'

```

### PR DESCRIPTION
**Pull request by rosik**
Fix:

- `integration.restart_replication.test_suggestions`
- `integration.api_query.test_suggestions`

I didn't forget about

- [x] Tests
- [x] ~~Changelog~~
- [x] ~~Documentation~~

Close #1530
Close #1552

### CODE REVIEW

**Review by yngvar-antonsson — APPROVED** [review]

File: test/integration/restart_replication_test.lua [hunk 1]
```diff
@@ -38,25 +38,30 @@ function g.test_suggestion()
...
+    end)
 
     g.A2.process:kill('STOP')
 
-    t.assert_equals(h.list_cluster_issues(g.A1), {replication_issue})
-    t.assert_equals(h.get_suggestions(g.A1).restart_replication, nil)
+    t.helpers.retrying({}, function()
+        t.assert_equals(h.list_cluster_issues(g.A1), {replication_issue})
+        t.assert_equals(h.get_suggestions(g.A1).restart_replication, nil)
+    end)
```
Comment (yngvar-antonsson) [inline test/integration/restart_replication_test.lua:54]:
```suggestion
t.assert_equals(h.list_cluster_issues(g.A1), {replication_issue})
t.assert_equals(h.get_suggestions(g.A1).restart_replication, nil)
```

File: test/integration/restart_replication_test.lua [hunk 2]
```diff
@@ -38,25 +38,28 @@ function g.test_suggestion()
...
+            {{uuid = g.A1.instance_uuid}}
+        )
+    end)
 
     g.A2.process:kill('STOP')
 
-    t.assert_equals(h.list_cluster_issues(g.A1), {replication_issue})
-    t.assert_equals(h.get_suggestions(g.A1).restart_replication, nil)
+t.assert_equals(h.list_cluster_issues(g.A1), {replication_issue})
+t.assert_equals(h.get_suggestions(g.A1).restart_replication, nil)
```
Comment (yngvar-antonsson) [inline test/integration/restart_replication_test.lua:52]:
```suggestion
    t.assert_equals(h.list_cluster_issues(g.A1), {replication_issue})
    t.assert_equals(h.get_suggestions(g.A1).restart_replication, nil)
```

**Review by Steap2448 — APPROVED** [review]

File: test/integration/restart_replication_test.lua [hunk 3]
```diff
@@ -38,12 +38,13 @@ function g.test_suggestion()
         message = "Replication from localhost:13302 (A-2)" ..
             " to localhost:13301 (A-1) isn't running",
     }
-
-    t.assert_equals(h.list_cluster_issues(g.A1), {replication_issue})
-    t.assert_items_equals(
-        h.get_suggestions(g.A1).restart_replication,
-        {{uuid = g.A1.instance_uuid}}
-    )
+    t.helpers.retrying({}, function()
```
Comment (rosik) [inline test/integration/restart_replication_test.lua:41]:
```suggestion
    h.retrying({}, function()
```

File: test/integration/restart_replication_test.lua [hunk 4]
```diff
@@ -52,11 +53,13 @@ function g.test_suggestion()
 
     g.A2.process:kill('CONT')
 
-    t.assert_equals(h.list_cluster_issues(g.A1), {replication_issue})
-    t.assert_items_equals(
-        h.get_suggestions(g.A1).restart_replication,
-        {{uuid = g.A1.instance_uuid}}
-    )
+    t.helpers.retrying({}, function()
```
Comment (rosik) [inline test/integration/restart_replication_test.lua:56]:
```suggestion
    h.retrying({}, function()
```
