### PR TITLE
Don't change password on restart

### LINKED ISSUE #1539: Fix flaky integration.zones.helpers.test_zones_distances
```
1) integration.zones.helpers.test_zones_distances
...work/cartridge/cartridge/test/integration/zones_test.lua:278: Content of the tables are not identical:
Expected: 
{
    z1 = {z1 = 0, z2 = 200, z3 = 100},
    z2 = {z1 = 1, z3 = 100},
    z3 = {z1 = 2, z2 = 50, z3 = cdata<void *>: NULL},
    z4 = {},
}
Actual: 
cdata<void *>: NULL
stack traceback:
	...work/cartridge/cartridge/test/integration/zones_test.lua:278: in function 'integration.zones.helpers.test_zones_distances'
	...
	[C]: in function 'xpcall'
```
[test.log](https://github.com/tarantool/cartridge/files/7008415/test.log)

### LINKED ISSUE #1546: Don't change password on start
Recently we've encountered an error on master restart:

```
Replication from open-bank-test-1:3502 (tdg-storage02-replica) to open-bank-test-3:3502 (tdg-storage02) state "stopped" (Transaction id must be equal to LSN of the first row in the transaction.)
```

Further investigation has shown that the problem was caused by the password change on cartridge start:

https://github.com/tarantool/cartridge/blob/8e57ed85398bb9b35fb21537460a468e1e7c08eb/cartridge/confapplier.lua#L493-L513

It should be conditional.

### PR DESCRIPTION
**Pull request by yngvar-antonsson**
I didn't forget about

- [x] Tests
- [x] Changelog

Close #1546 

Also close #1539

### CODE REVIEW

File: test/integration/master_restart_test.lua [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+        box.space.test:insert{2}
+        box.space.test:insert{3}
+        box.commit()
+    ]])
+
+    -- check that data replicated
+    local content = g.cluster:server('replica').net_box:eval([[
+        return box.space.test:select()
+    ]])
+    t.assert_equals(content, {{1}, {2}, {3}})
```
Comment (rosik) [inline test/integration/master_restart_test.lua:59]: It may be flaky. The replication is async. Wrap it with `helpers.retrying`

File: cartridge/confapplier.lua [hunk 2]
```diff
@@ -504,11 +504,21 @@ local function boot_instance(clusterwide_config)
...
         end
 
-        BoxError:pcall(
-            box.schema.user.passwd,
-            username, password
-        )
+        local user = box.space[box.schema.USER_ID].index.name:get(username)
+        local change_passwd = true
+        if user ~= nil then
+            local old_passwd = user[5]['chap-sha1']
```
Comment (rosik) [inline cartridge/confapplier.lua:510]: What's 5?

File: cartridge/confapplier.lua [hunk 3]
```diff
@@ -504,11 +504,21 @@ local function boot_instance(clusterwide_config)
...
+                change_passwd = false
+            end
+        end
 
+        if change_passwd then
+            BoxError:pcall(
+                box.schema.user.passwd,
+                username, password
+            )
+        end
```
Comment (rosik) [inline cartridge/confapplier.lua:521]: It looks too complicated. I'm sure it could be more concise

File: test/integration/master_restart_test.lua [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+                        alias = 'master',
+                        instance_uuid = helpers.uuid('a', 'a', 1),
+                        -- advertise_port = 13301,
+                    },
+                    {
+                        alias = 'replica',
+                        instance_uuid = helpers.uuid('a', 'a', 2),
+                        -- advertise_port = 13301,
+                    }
+                },
```
Comment (rosik) [inline test/integration/master_restart_test.lua:27]: It could be briefer.

File: test/integration/master_restart_test.lua [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+
+    -- check that data still on replica
+    local content = g.cluster:server('replica').net_box:eval([[
+        return box.space.test:select()
+    ]])
+    t.assert_equals(content, {{1}, {2}, {3}})
+
+    local info_replication = g.cluster:server('master').net_box:eval([[
+        return box.info.replication
+    ]])
```
Comment (rosik) [inline test/integration/master_restart_test.lua:76]: I suggest checking something like 
```
t.assert_covers(
    box.info.replication,
    {status = 'running'}
)
```

File: cartridge/confapplier.lua (hunk 2 above)
Comment (rosik) [reply cartridge/confapplier.lua:510]: Even if there's no built-in constant, add a comment (preferably with a link to the code or spec)

File: test/integration/master_restart_test.lua [hunk 6]
```diff
@@ -0,0 +1,83 @@
+local fio = require('fio')
+local t = require('luatest')
+local g = t.group()
+
+local helpers = require('test.helper')
```
Comment (rosik) [inline test/integration/master_restart_test.lua:5]: Please, use modern style:

```lua
local t = require('luatest')
local h = require('test.helper')
local g = t.group()
```

File: test/integration/master_restart_test.lua [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+
+g.before_each(function()
+    g.cluster = helpers.Cluster:new({
+        datadir = fio.tempdir(),
+        server_command = helpers.entrypoint('srv_basic'),
+        cookie = require('digest').urandom(6):hex(),
```
Comment (rosik) [inline test/integration/master_restart_test.lua:11]: `cookie = h.random_cookie(),`

File: test/integration/master_restart_test.lua [hunk 8]
```diff
@@ -0,0 +1,83 @@
...
+        replicasets = {
+            {
+                uuid = helpers.uuid('a'),
```
Comment (rosik) [inline test/integration/master_restart_test.lua:14]: It may be omitted nowadays

**Review by rosik — COMMENTED** [review]
In general, it looks appropriate, but there's a lot of NITs, find them below.

File: test/integration/master_restart_test.lua (hunk 6 above)
Comment (rosik) [reply test/integration/master_restart_test.lua:5]: See, for example, https://github.com/tarantool/cartridge/blob/master/test/integration/restart_replication_test.lua

File: test/integration/master_restart_test.lua [hunk 9]
```diff
@@ -0,0 +1,83 @@
...
+
+    local info_replication = g.cluster:server('master').net_box:eval([[
+        return box.info.replication
+    ]])
+
+    -- check that data restored on master
+    local content = g.cluster:server('master').net_box:eval([[
+        return box.space.test:select()
+    ]])
+    t.assert_equals(content, {{1}, {2}, {3}}, info_replication[2].upstream.message)
```
Comment (rosik) [inline test/integration/master_restart_test.lua:82]: It's potentially flaky too.

File: cartridge/confapplier.lua [hunk 10]
```diff
@@ -504,11 +504,19 @@ local function boot_instance(clusterwide_config)
...
-            username, password
-        )
 
+        local user = box.space[box.schema.USER_ID].index.name:get(username)
+
+        if user == nil
+        or user[5]['chap-sha1'] ~= box.schema.user.password(password)
+        -- check that password is changed
+        -- https://github.com/tarantool/tarantool/blob/ed7da7e638f4b6d56c32fcaae5a7fb04a813eb5b/src/box/lua/schema.lua#L2752-L2757
+        then
```
Comment (rosik) [inline cartridge/confapplier.lua:514]:
```suggestion
        -- https://github.com/tarantool/tarantool/blob/2.7.3/src/box/lua/schema.lua#L2719-L2724
        -- Don't commit anything if it's already ok.
        if user == nil or user.auth['chap-sha1'] ~= box.schema.user.password(password) then
```

File: test/integration/master_restart_test.lua [hunk 11]
```diff
@@ -0,0 +1,80 @@
...
+    -- check that data still on replica
+    local content = g.replica.net_box:eval([[
+        return box.space.test:select()
+    ]])
+    t.assert_equals(content, {{1}, {2}, {3}})
+
+    t.helpers.retrying({}, function()
+        local info_replication = g.master.net_box:eval([[
+            return box.info.replication
+        ]])
```
Comment (rosik) [inline test/integration/master_restart_test.lua:72]: I suggest adding one more `assert_covers` instead of putting it into the error message

**Review by rosik — CHANGES_REQUESTED** [review]

**Comment by yngvar-antonsson** [comment]
lgtm

**Review by rosik — APPROVED** [review]
