### PR TITLE
Fix cartridge.cfg params description

### LINKED ISSUE #1596: cartridge.cfg params aren't described enough
- `bucket_count` could be set only once, before first cluster start
- `vshard_groups` could be set with two notations:

```lua
vshard_groups = {
        -- both notations are valid
        ['cold'] = {bucket_count = 2000},
        'hot',
    },
```

### PR DESCRIPTION
**Pull request by yngvar-antonsson**
I didn't forget about

- [x] Documentation

Close #1596

### CODE REVIEW

File: cartridge.lua [hunk 1]
```diff
@@ -159,12 +159,17 @@ end
 --
 -- @tparam ?number opts.bucket_count
 --  bucket count for vshard cluster. See vshard doc for more details.
+--  Could be set only **once**, before first cartridge start and coundn't be
```
Comment (NickVolynkin) [inline cartridge.lua:162]: Why in the past tense? 
```suggestion
--  Can be set only **once**, before the first run of Cartridge application, and can't be
```

**Review by NickVolynkin — APPROVED** [review]
